# Generated by Django 5.0.3 on 2024-03-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.TextField(max_length=255)),
                ('email_usuario', models.TextField(max_length=255)),
            ],
        ),
    ]
